### PR TITLE
PER-13 Updated the ID repo Helper and Test Script

### PR DESCRIPTION
**Pull request by Sanjayss04**
Updated the ID Repo Helper and Test Script with some minor modifications. 

- Added correct authorization in the headers.
- Added response code assertion.
- Updated the add identity request.

### CODE REVIEW

**Comment by nihallakshmankonchady** [comment]
@Sanjayss04 , Please find my reviews:
1. Under **Retrieve Identity using UIN (Execution)** .  sampler is named as Retrieve Identity using UIN.
2. Under **Retrieve Identity using VID (Execution)**. sampler is named as  Retrieve Identity using VID.
3. Under **Add Identity (Execution)**. sampler is named as  Add Identity (bio).
4. Under **Update Identity (Execution)**. sampler is named as  Update Identity Execution.
5. Under **Create VID (Execution)**. sampler is named as  Create VID Execution.
6. Under **Update VID (Preparation)**. Validate __StringtoFile function in Beanshell post-processor.
7. Under **Update VID (Execution)**. sampler is named as  Update VID Execution.
8. Under **Auth Type Status (Execution)**. sampler is named as  Auth Type Status Execution.
9. Under **Create Draft (Execution)**. sampler is named as  Create Draft API Execution.
10. Under **Update Draft (Execution)**. sampler is named as  Update Draft API Execution.
11. Under **Get Draft (Execution)**. sampler is named as  Get Draft API Execution.
12. Under **Publish Draft (Execution)**. sampler is named as  Publish Draft API Execution.

**Comment by Sanjayss04** [comment]
> @Sanjayss04 , Please find my reviews:
> 
> 1. Under **Retrieve Identity using UIN (Execution)** .  sampler is named as Retrieve Identity using UIN.
> 2. Under **Retrieve Identity using VID (Execution)**. sampler is named as  Retrieve Identity using VID.
> 3. Under **Add Identity (Execution)**. sampler is named as  Add Identity (bio).
> 4. Under **Update Identity (Execution)**. sampler is named as  Update Identity Execution.
> 5. Under **Create VID (Execution)**. sampler is named as  Create VID Execution.
> 6. Under **Update VID (Preparation)**. Validate __StringtoFile function in Beanshell post-processor.
> 7. Under **Update VID (Execution)**. sampler is named as  Update VID Execution.
> 8. Under **Auth Type Status (Execution)**. sampler is named as  Auth Type Status Execution.
> 9. Under **Create Draft (Execution)**. sampler is named as  Create Draft API Execution.
> 10. Under **Update Draft (Execution)**. sampler is named as  Update Draft API Execution.
> 11. Under **Get Draft (Execution)**. sampler is named as  Get Draft API Execution.
> 12. Under **Publish Draft (Execution)**. sampler is named as  Publish Draft API Execution.


@nihallakshmankonchady 
Have updated the Test Script with required changes. Please review.

**Comment by nihallakshmankonchady** [comment]
Hi @Sanjayss04 ,
can you please change the & to \,
Under Update VID (Preparation). Validate __StringtoFile function in Beanshell post-processor **Store UIN-VID To File**.
**${__StringToFile(uinAndVidGenerated.txt,${uin}&${vidGenerated}\n,true,)}**

**Comment by Sanjayss04** [comment]
> Hi @Sanjayss04 , can you please change the & to , Under Update VID (Preparation). Validate __StringtoFile function in Beanshell post-processor **Store UIN-VID To File**. **${__StringToFile(uinAndVidGenerated.txt,${uin}&${vidGenerated}\n,true,)}**


@nihallakshmankonchady Have updated the same, pls check.

**Comment by nihallakshmankonchady** [comment]
@Sanjayss04 , Review has been done from my side.

**Review by vishwa-vyom — APPROVED** [review]
Since these changes are not scenario based and one round of review is already performed by @nihallakshmankonchady, approving the PR without full review.

**Pull request merged**
