### PR TITLE
PER-17 Updated the Pre-reg Scripts with minor modifications

### PR DESCRIPTION
**Pull request by Sanjayss04**
Updated the existing Pre-reg Scripts with minor modifications : 

- Added the correct auth token in the headers. 
- Added correct response assertions. 
- Corrected the naming convention.

### CODE REVIEW

**Comment by nihallakshmankonchady** [comment]
Hi @Sanjayss04 ,

Is it possible to add assertion for sampler **Select PreRegIds From DB** from **script Prereg_Get_Prereg_ID's_From_DB.jmx**

**Comment by Sanjayss04** [comment]
> 

Yes it is possible. Have added 200 response code assertion to the script.

**Comment by nihallakshmankonchady** [comment]
@Sanjayss04 .. I will reviewed your PR.

**Review by vishwa-vyom — APPROVED** [review]
Approving based on @nihallakshmankonchady approval

**Pull request merged**
