### PR TITLE
PER-42 Updated the Packet Manager scripts with minor modifications.

### PR DESCRIPTION
**Pull request by Sanjayss04**
Updated the Packet Manager Helper and Test Script with some minor modifications.

- Updated the CSV file with correct values. The endpoints are running fine now.
- Added response code assertion. 
- Corrected the naming convention of test data files which are used in the Test Script.

### CODE REVIEW

**Comment by nihallakshmankonchady** [comment]
Please remove "Execution" in sampler naming.

**Comment by Sanjayss04** [comment]
> Please remove "Execution" in sampler naming.

**Comment by Sanjayss04** [comment]
> Please remove "Execution" in sampler naming.

Okay @nihallakshmankonchady On the basis of perf script guide docs, once lets decide what exactly needs to be followed. Will update accordingly.

**Comment by Sanjayss04** [comment]
> Please remove "Execution" in sampler naming.

@nihallakshmankonchady Have updated the same. Please review

**Comment by nihallakshmankonchady** [comment]
@Sanjayss04 , I have reviewed your scripts.

**Review by vishwa-vyom — APPROVED** [review]
Since these changes are not scenario based and one round of review is already performed by @nihallakshmankonchady, approving the PR without full review.

**Pull request merged**
