### PR TITLE
PER-110, PER-111, PER-112, PER-113, PER-114, PER-115, PER-132, PER-133 Updated the Regproc Helper and Test Scripts to Scenario approach

### PR DESCRIPTION
**Pull request by Sanjayss04**
Updated the Regproc Packet generation, Helper and Test Scripts with some minor modifications.

- In Helper script generating auth token for both Regproc and Resident client.
- Updated few fields in Create Context Endpoint API while generating packets. 
- For Zip packet added - v1/packetcreator/packetcreator/${contextKeyValue} endpoint.
- Added correct response assertions.
- Corrected the naming convention.

### CODE REVIEW

**Comment by nihallakshmankonchady** [comment]
Hi @Sanjayss04 ,

Please find my review comments below.
Under test Script.
1.Upload Registration Packet (Execution) - There is disabled constant timer
2. Get Packet status (Preparation) - There is constant timer and no assertions are present at each sampler.
 

RegProc Helper script:
1. Remove the secret values in user defined variables.

Generator script.
1. Zip Packet Endpoint API - It has only 200 response code assertion

**Comment by Sanjayss04** [comment]
> Under test Script. 1.Upload Registration Packet (Execution) - There is disabled constant timer - Have deleted the disabled constant timer.
2. Get Packet status (Preparation) - There is constant timer and no assertions are present at each sampler. - Yes the contant timer is added because it takes a bit of time for the packet to get processed, so constant timer was already present in the script. We are using beanshell sampler there so no assertions were added in this.
> 
> RegProc Helper script:
> 
> 1. Remove the secret values in user defined variables. - Removed the secret values.
> 
> Generator script.
> 
> 1. Zip Packet Endpoint API - It has only 200 response code assertion - Yes, because in response we get a packet path and that can be different depending on the machine we are testing the scripts, so only 200 response assertion is added.

**Comment by nihallakshmankonchady** [comment]
@Sanjayss04 .. i have reviewed it.

**Comment by Sanjayss04** [comment]
@vishwa-vyom PFA updated PR for Reg proc module endpoints converted into scenario approach.

Updates in the PR :- 

- Packet Generation script is deleted and the thread groups are added in the Reg proc Test Script. 
- Scripts are converted into Scenario approach. 
- Constant Throughput Timer has been added to all the thread groups. 
- Added correct response assertions.

**Comment by akhilmoogi** [comment]
In packet generation thread group, should we not parameterize the field variables?

**Comment by Sanjayss04** [comment]
> In packet generation thread group, should we not parameterize the field variables?

I have parameterized few of the main fields which are required like userID, machineID, centerID, password, serverIP, contextKeyValue, mountPath and authCertsPath. 

Earlier even these values were not parameterized.

**Comment by akhilmoogi** [comment]
In Create Persona Endpoint for gender attribute, can we add all genders?

**Comment by akhilmoogi** [comment]
Can we also add the helper script as part of reg proc main script under preparation and setup?

**Comment by Sanjayss04** [comment]
> In Create Persona Endpoint for gender attribute, can we add all genders?

Done

**Comment by Sanjayss04** [comment]
> Can we also add the helper script as part of reg proc main script under preparation and setup?

Done

**Comment by Sanjayss04** [comment]
Closing this PR. 

- Script needs to be reworked according to Regproc scenario request page. 
- Internal Handover of the the script to Performance team.

**Pull request closed without merging**
